apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::897839913011:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-16NNTFRH6SHQ3
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-21T14:56:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "913"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 68000a7e-a9f9-43cd-a9e9-e34e98b50d75
